### ISSUE TITLE
Show the time when charge will be completed

### ISSUE THREAD

**Issue by amund7** [jpasqua/VisibleTesla#116]
(feature request)
Right now my VT says charging will be done in 7:55.
I'd like to see VT simply calculate 7:55 + DateTime.Now, so I know at what time it's ready tomorrow without having to look at the clock and do head maths.

**Comment by jpasqua** [comment]
A preference will be added for this similar to the one that allows you to select which Range type is displayed on the Overview Tab.

**Comment by amund7** [comment]
That is great, thanks!

**Comment by jpasqua** [comment]
Code and docs checked in.
