### ISSUE TITLE
Refuses to start on OpenJDK

### ISSUE THREAD

**Issue by psy-q** [jpasqua/VisibleTesla#78]
I'm using OpenJDK:

```
java version "1.7.0_55"
OpenJDK Runtime Environment (IcedTea 2.4.7) (7u55-2.4.7-1)
OpenJDK 64-Bit Server VM (build 24.51-b03, mixed mode)
```

And get an error that the Java version isn't new enough. Does VisibleTesla really require Java 8/JDK 1.8?

**Comment by petersvei** [comment]
Hi there, I'm having te same issue when trying to build with ant on Ubuntu with open jdk and on even on windows with oracle jdk 1.7.0_60.

Any suggestions would be highly appreciated.
